export const constant = {
  IS_USER_LOGIN: 'IS_USER_LOGIN',
  Products: 'Products',
  SEARCH_PLACEHOLDER: 'Search product here...',
  SEARCH_PRODUCT: 'Search Product',
  PRODUCT_ADDED_SUCCESS_MSG: 'Product added successfully !!!',
  ADD_NEW_PRODUCT_TITLE: 'Add New Product Detail',
  TITLE: 'Title',
  DESCRIPTION: 'Description',
  PRICE: 'Price',
  SAVE_PRODUCT: 'Save Product',
  LOGIN: 'Login',
  ENTER_USERNAME: 'Enter Username',
  ENTER_PASSWORD: 'Enter password',
  PRODUCT_DETAIL: 'Product Detail',
  USER_PROFILE: 'User Profile',
  LOGOUT: 'Logout',
  GENDER: 'Gender',
  USERNAME: 'Username',
  EMAIL: 'Email',
  NAME: 'Name',
  LOGIN_SUCCESS_MSG:'Login successful !!!',
  LOGIN_FAILED: 'Login failed.',
  INVALID_CRED:'Invalid credentials',
  NO_DATA_FOUND:'No Product Found. ',
  SCREEN_PRODUCT_DETAIL:'AddNewProduct',
  SCREEN_ADD_NEW_PRODUCT:'AddNewProduct',
};
